### PR TITLE
Update Three.js and Ensure Compatibility with Three.js USDZ Exporter

### PR DESCRIPTION
**Pull request by Jamedie**
Hello, I'm not sure if this project is still actively maintained, but I've incorporated it into one of my projects. I've updated the version of Three.js and modified the default parameter of 'undefined' for your HydraMaterial to ensure compatibility with the USDZ exporter from Three.js, as 'undefined' parameters are not supported by it.

### CODE REVIEW

**Review by dongho-shin — APPROVED** [review]
LGTM

**Comment by digitalw** [comment]
@ponahoum  Is there anything stopping you from merging this and making a new version? please reach out to us if you need any help maintaining this. I am sure the community would be glad to help.

**Comment by ponahoum** [comment]
@Jamedie @digitalw I'm not actively maintaining this project as I'm busy with work and other projects. The PR looks good though, I'll test and merge this week.

@digitalw, feel free to contribute; I'm always available for PRs and associated releases if a few people need it. Just mention me in a PR/issue channel. By the way, did this PR fix the texture issue you mentionned #13 here ?

Note that I also worked on another version with the latest USD framework version a few months ago (to fix some texture bugs notably), but I couldn't release it due to a lack of time. The setup of the USD/autodesk project is quite painful and doesn't make the development easy.

**Comment by digitalw** [comment]
Hi @ponahoum 
Thanks, I really appreciate all your work. I have not actually tested that branch for myself. 

Seeing that you do not have the time to work on this (Not trying to to be disrespectful, we all need to put food on our tables, and we have other responsibilities, projects, you name it ) maybe the efforts could be joined with the current official three usdz loader: https://github.com/mrdoob/three.js/issues/28693

**Comment by ponahoum** [comment]
@digitalw Totally agree; I also prefer "official" solutions  and I really hope ThreeJS will manage to include a complete USD loader in their solution. Although, I think one of the major challenges of ThreeJS will be to completely integrate USD without using the C++ SDK (i think they don't want to put wasm like code in the library, which is understandable). But this task is quite complete as the USD format is complex.

For now, I'll just maintain this repo to the bare minimum, until ThreeJS offers a complete solution. I would not encourage people in general to contribute to this repo, but rather to an official solution for threejs.

Regarding this MR, I see no specific issue other than to upgrade to the latest version of three. I'll do it and will include your modification in it.

**Comment by ponahoum** [comment]
#17

**Comment by ponahoum** [comment]
v1.0.8 includes a variation of this fix (instead of setting to null or undefined, we don't do anything, which should prevent the material corruption). Therefore closing this PR. Don't hesitate to re-open if the fix doesn't suit your needs !

**Pull request closed without merging**
